---
title: "Batter Analysis"
author: "T Baynes"
date: "December 24, 2015"
output: html_document
---

Let's do some analysis on batting statistics.

First lets run the code that processes all the raw files from Cricsheet:

```{r, message = FALSE, error = FALSE, warning = FALSE}
source("process_cricsheet.R")
```

Let's calculate runs, balls faced and strike rate, broken down by whether the performance was in a winning or losing cause.
```{r}


batter_summary <- ball_by_ball_df %>%
  group_by(batsman, batter_wins) %>%
  summarise(balls_faced = n(),
            runs = sum(`runs-batsman`)) %>%
  mutate(strike_rate = runs / balls_faced) 

```


Ok, now some plots


```{r}
ggplot(batter_summary, aes(x = balls_faced, y = runs)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, colour = "Blue") 
```

```{r}
ggplot(batter_summary, aes(x = strike_rate, y = runs)) + 
  geom_point() 
```

Let's break these charts out to separate performances in winning and losing causes

```{r}
ggplot(batter_summary, aes(x = balls_faced, y = runs)) + 
  geom_point() +
  geom_abline(intercept = 0, slope = 1, colour = "Blue") +
  facet_wrap(~batter_wins)
```

```{r}
ggplot(batter_summary, aes(x = strike_rate, y = runs)) + 
  geom_point() +
  facet_wrap(~batter_wins)
```